version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.10.0
    working_directory: ~/tehbot/src
    steps:
      - checkout:
          path: ~/tehbot/src
      - run:
          command: ls /home/circleci/tehbot/src/
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm ci
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build app
          command: npm run tsc
      - save_cache:
          key: v1-build-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - .build
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - add_ssh_keys:
          fingerprints:
            - "b5:de:74:77:84:ac:c5:60:d6:ef:14:b1:e4:63:60:c6"
      - run:
          command: ls
      - run:
          command: pwd
      - run:
          name: Copy to server
          command: |
            scp -o StrictHostKeyChecking=no -r . $TEHBOT_LIGHTSAIL_USERNAME@$TEHBOT_LIGHTSAIL_PUBLIC_IP:/home/${TEHBOT_LIGHTSAIL_USERNAME}/app/bot/tehbot
      - run:
          name: Run deploy script
          command: |
            ssh -o StrictHostKeyChecking=no $TEHBOT_LIGHTSAIL_USERNAME@$TEHBOT_LIGHTSAIL_PUBLIC_IP "./scripts/deploy.sh"
